#!/usr/bin/env perl
use Mojolicious::Lite;
plugin 'BootstrapHelpers';

my $name;
my $mail; 
my $entry;
my @entries = ();

get '/' => sub {
  my $c = shift;
  $c->stash(name => \$name);
  $c->stash(mail => \$mail);
  $c->stash(entries => \@entries);
  $c->render('index');
};

post '/post' => sub {
  my $c = shift;
  my $name = $c->param('name');
  my $mail = $c->param('mail');
  my $entry = $c->param('body');
  my $bord = {
    name => $name,
    mail => $mail,
    entry => $entry,
  };
  if ($mail eq 'age') {
    unshift @entries,$bord;
  }else{
    push @entries, $bord;
  }
  $c->redirect_to('/');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title '入力フォーム';
%= form_for '/post' => method => 'POST' => begin
  %= text_field 'name'
  %= text_field 'mail'
  %= text_field 'body'
  %= submit_button '投稿する'
% end

% my $num = 0;
% for my $i (@{$entries}) {
% $num++;
  <p><%= $num %>. name: <%= $i->{name} %> mail: <%= $i->{mail} %></p>
  <p><%= $i->{entry} %></p>
% }

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>

